# Generated by Django 3.2.16 on 2024-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20241213_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=30, verbose_name='Фамилия'),
        ),
    ]
